# currency: EUR

# grid: # price using energy from the grid
#   type: fixed
#   price: 0.294 # EUR/kWh

# feedin: # price for feeding solar energy to the grid
#   type: fixed
#   price: 0.08 # EUR/kWh

# co2: # carbon intensity forecast data
#   type: gr√ºnstromindex
#   zip: <zip>
