name: Deploy updated templates

on:
  push:
    branches: [master]
    paths: "templates/**"
  workflow_dispatch:

jobs:
  docupdate:
    name: Deploy updated templates
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install tools
        run: make install

      - name: Build docs
        run: make docs

      # - name: Clean git
      #   run: |
      #     git checkout go.*
      #     rm -rf flags buildflags

      - name: Deploy to docs repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./templates/docs
          external_repository: evcc-io/docs
          publish_branch: main
          destination_dir: templates
          allow_empty_commit: false
          commit_message: Templates update
        if: ${{ success() }}
