name: Deploy data to website
permissions:
  contents: read

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  brandupdate:
    name: Deploy data to website
    runs-on: depot-ubuntu-24.04-arm

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go

      - name: Build docs
        run: make install docs

      - name: Remove .gitignore to allow brands.json to be committed
        run: rm templates/evcc.io/.gitignore

      - name: Deploy to evcc.io repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.WEBSITE_DEPLOY_TOKEN }}
          publish_dir: ./templates/evcc.io/
          external_repository: evcc-io/evcc.io
          publish_branch: main
          destination_dir: data
          allow_empty_commit: false
          commit_message: Brand data update
        if: success()
