name: Deploy data to website

on:
  push:
    branches: [master]
    paths: ["templates/evcc.io/**"]
  workflow_dispatch:

jobs:
  brandupdate:
    name: Deploy data to website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Build docs
        run: make install docs

      - name: Deploy to evcc.io repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./templates/evcc.io/
          external_repository: evcc-io/evcc.io
          publish_branch: main
          destination_dir: data
          allow_empty_commit: false
          commit_message: Brand data update
        if: ${{ success() }}
